### ISSUE TITLE
Link to Organizing multiple accounts whitepaper

### ISSUE THREAD

**Issue by shankey28** [awsdocs/aws-control-tower-guide#23]
Since the below Control Tower documentation page talks about multi-account strategy, it might be a good idea to refer to the whitepaper published regarding Organizing multiple accounts using AWS Organizations.

## Control Tower documentation page
https://docs.aws.amazon.com/controltower/latest/userguide/aws-multi-account-landing-zone.html#guidelines-for-multi-account-setup

## Whitepaper
https://docs.aws.amazon.com/whitepapers/latest/organizing-your-aws-environment/benefits-of-using-multiple-aws-accounts.html

**Comment by lundql** [comment]
Hello, this link already exists. Thanks!
