### ISSUE TITLE
AWSControlTowerBP-BASELINE-CONFIG-MASTER is incorrectly listed in the StackSets section

### ISSUE THREAD

**Issue by bmorrissirromb** [awsdocs/aws-control-tower-guide#40]
AWSControlTowerBP-BASELINE-CONFIG-MASTER is deployed as a Stack in the management account. In https://github.com/awsdocs/aws-control-tower-guide/blob/main/doc_source/how-control-tower-works.md, the documentation incorrectly lists it as being deployed in the StackSets section.

**Comment by lundql** [comment]
This has been fixed, thank you.
